name: CI

on: [push]

env:
  BUILD_TYPE: release
  OTHER_PROJECTS: "mulle-objc/mulle-objc-developer;
mulle-c/mulle-c-developer;"

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ ubuntu-latest]

    steps:
    - name: Update stuff (for act)
      if: ${{ env.ACT }}
      run: apt-get update

    - name: Install stuff (for act)
      if: ${{ env.ACT }}
      run: apt-get -y install cmake curl lsb-release uuid-runtime

    - name: Set MULLE_HOSTNAME
      run: |
        name="${GITHUB_REF##*/}"
        MULLE_HOSTNAME="ci-${name##*-}"
        echo "MULLE_HOSTNAME=${MULLE_HOSTNAME}" >> $GITHUB_ENV

    - name: Add to path
      run:  echo "$HOME/bin" >> $GITHUB_PATH

    - name: Dump Environment
      run:  env | sort

    - uses: actions/checkout@v2
      if: ${{ ! env.ACT }}

    - uses: mulle-sde/github-ci@v1

    - name: Dump Project Environment
      run:  |
        ls -l .mulle/etc/env/
        mulle-sde environment

    - name: Mulle-SDE Fetch
      run: mulle-sde fetch

    - uses: mulle-objc/github-ci@v2

    - name: Mulle-SDE Craft
      run: mulle-sde craft --${BUILD_TYPE:-release}

    - name: Mulle-SDE Test
      run: |
        [ ! -d test ] || mulle-sde test
